name: "helm-eks"
description: "Github Action to work with helm charts & AWS EKS."
author: "Pierre DEMAGNY"
branding:
  icon: "terminal"
  color: "blue"
inputs:
  command:
    description: "The command(s) to run."
    required: true
  eksClusterName:
    description: "Name of the EKS cluster operate on."
    required: true
  awsAccessKeyId:
    description: "Your AWS access key id to get the cluster context."
    required: true
  awsSecretAccessKey:
    description: "Your AWS Secret access key to get the cluster context."
    required: true
  awsDefaultRegion:
    description: "Your AWS region to get the cluster context."
    required: false
    default: "eu-west-1"
  helmVersion:
    description: "helm version to install."
    required: false
    default: "2.14.0"
  helm3Version:
    description: "helm3 version to install."
    required: false
    default: "3.4.0"
  kubectlVersion:
    description: "kubectl version to install."
    required: false
    default: "1.13.9"
runs:
  using: "docker"
  image: "docker://lifepal/helm-eks:v2"
  args:
    - ${{ inputs.command }}
    - ${{ inputs.eksClusterName }}
    - ${{ inputs.awsAccessKeyId }}
    - ${{ inputs.awsSecretAccessKey }}
    - ${{ inputs.awsDefaultRegion }}
    - ${{ inputs.helmVersion }}
    - ${{ inputs.kubectlVersion }}
